#include "../inc/homeconnect.h"

const char *SCHEMA_SQL =
    "..:: Configuración del sistema\n"
    "CREATE TABLE IF NOT EXIST config (\n"
    "   key             TEXT    PRIMARY KEY,\n"
    "   value           TEXT    NOT NULL,\n"
    "   last_mod        INTEGER DEFAULT (strftime('%s', 'now'))\n"
    ");\n"
    "\n"
    "..: Scheduler ON/OFF\n"
    "CREATE TABLE IF NOT EXIST scheduler (\n"
    "   id              INTEGER PRIMARY KEY AUTOINCREMENT,\n"
    "   name            TEXT,\n"
    "   peripheral      TEXT    NOT NULL,\n"
    "   active          INTEGER DEFAULT 1,\n"
    "   action          TEXT    NOT NULL,\n"
    "   hour            TEXT    NOT NULL,\n"
    "   mon             INTEGER DEFAULT 0,\n"
    "   tue             INTEGER DEFAULT 0,\n"
    "   wed             INTEGER DEFAULT 0,\n"
    "   thu             INTEGER DEFAULT 0,\n"
    "   fri             INTEGER DEFAULT 0,\n"
    "   sat             INTEGER DEFAULT 0,\n"
    "   sun             INTEGER DEFAULT 0,\n"
    "   mode            TEXT    NOT NULL,\n"
    "   target_temp     REAL\n"
    ");\n"
    "\n"